import type { Metadata } from "next";
import { Inter, Antonio } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footerSection.jsx/Footer";
import MarqueeSection from "@/components/marqueeSection/MarqueeSection";
import ReactLenis from "lenis/react";
import CustomCursor from "@/components/CustomCursor";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const antonio = Antonio({
  variable: "--font-antonio",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${antonio.variable} antialiased`}>
        <ReactLenis root>
          <Navbar />
          <CustomCursor />
          {children}
          <MarqueeSection />
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
